### ISSUE TITLE
Implement RPC Monitor "Batch Mode" Driver

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/RPCMonitor#2]
### Tasks
- [x] Read file specified via configuration
- [x] Split file into individual pieces
- [x] Feed individual pieces into the pipeline
- [x] Document file formats (via wiki?)
