### ISSUE TITLE
Create Test RPC Sequences from Existing VAM Captures

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/RPCMonitor#4]
### Tasks
- [x] Create 'Green path' RPC Sequence from CPRS (login, patient select, log out)
- [x] Create 'Test/Error path' RPC Sequence (1/3 valid RPCs, 1/3 invalid RPCs, 1/3 unrecognized RPCs)
- [x] Document the format of the raw data files (raw data strings? JSON objects)
