### ISSUE TITLE
Dockerize RPC Monitor

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/RPCMonitor#5]
### Tasks
- [x] Create Dockerfile for the application
- [x] Bundle default RPC files
- [x] Document setup/operation
